# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Pan
tagline:          'Yet another blog'
description:      ''
url:              https://revlis7.github.io
baseurl:          https://revlis7.github.io/

author:
  name:           'Kevin Pan'
  url:            https://twitter.com/revlis7

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/revlis7
